### ISSUE TITLE
Use of undefined constant

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/elysia_cron#4]
I got this warning while using drush to clear the cache:

```
Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_FULL - assumed 'DRUSH_BOOTSTRAP_BACKDROP_FULL' (this will throw an Error in a [warning]
future version of PHP) elysia_cron.drush.inc:71
```

**Comment by herbdool** [comment]
Hi Robert. Thanks for the fix. I think putting it in quotes isn't the fix needed here. Instead I think it needs to be changed to `BOOTSTRAP_FULL` as is set in https://github.com/backdrop-contrib/drush/blob/1.x-0.x/BackdropBoot.php

I didn't realize that it uses a different format for the constants.

**Comment by herbdool** [comment]
I also wonder if it needs to be in this format: `BackdropBoot::BOOTSTRAP_FULL` since it's defined in a class. Are you able to try it out Robert?

**Comment by robertgarrigos** [comment]
using `BackdropBoot::BOOTSTRAP_FULL`:

```
Error: Class &#039;BackdropBoot&#039; not found a elysia_cron_drush_command() (línia 72 de /home/robert/garrigos/www/modules/contrib/elysia_cron/elysia_cron.drush.inc).
Drush command terminated abnormally due to an unrecoverable error.
```
Using `BOOTSTRAP_FULL`:
 
```
Use of undefined constant BOOTSTRAP_FULL - assumed 'BOOTSTRAP_FULL' (this will throw an Error in a future version of PHP)        [warning]
elysia_cron.drush.inc:72
'all' cache was cleared.
```

**Comment by herbdool** [comment]
@serundeputy do you recommend a best approach? We might be able to access the Drupal constants but that's not future proof.

**Comment by herbdool** [comment]
For now I think drush relies on a base that sets some constants for Drupal so `DRUSH_BOOTSTRAP_DRUPAL_FULL` might work too. Ideally we'd use a backdrop version.

**Comment by serundeputy** [comment]
@robertgarrigos @herbdool something like this i think: https://github.com/backdrop-contrib/drush/blob/1.x-0.x/commands/config/backdrop_config_export.drush.inc#L19

**Comment by robertgarrigos** [comment]
This actually worked without any error. Thanks @serundeputy. Should I update the pr with this, @herbdool ?

**Comment by robertgarrigos** [comment]
Updated the pr

**Comment by herbdool** [comment]
Thanks Robert!

**Comment by herbdool** [comment]
One more change, Robert. It should be FULL not SITE.

**Comment by herbdool** [comment]
Merged. Thanks @robertgarrigos and @serundeputy

**Comment by robertgarrigos** [comment]
thank you @herbdool
